version: 2

project_name: lpm

before:
  hooks:
    - go mod tidy

builds:
  - binary: lpm
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - "7"
    ignore:
      - goos: windows
        goarch: arm
      - goos: darwin
        goarch: arm
    ldflags:
      - -s -w -X main.version=1.0.0

archives:
  - format: tar.gz
    name_template: "lpm_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "lpm_checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - Merge pull request
      - Merge branch
