#include "base.hpp"
#include "cli_base.hpp"
#include "commands.hpp"
#include "curl/curl.h"
#include "fsio.hpp"
#include <algorithm>
#include <cstddef>
#include <filesystem>
#include <fstream>
#include <iostream>
#include <sstream>
#include <stdexcept>
#include <string>

static const std::string build_file_string(const char *github_url) {
  std::string url = github_url;

  // remove o prefixo do github se existir
  const std::string prefix = "https://github.com/";
  if (url.rfind(prefix, 0) == 0)
    url = url.substr(prefix.size());

  // remove .git se existir
  if (url.size() > 4 && url.substr(url.size() - 4) == ".git")
    url = url.substr(0, url.size() - 4);

  std::string _space = "  ";
  std::stringstream str;
  std::string _end = "\n";
  str << "-- file automatically generated by lpm.\n";
  str << "return {" << _end;
  str << _space << "'" << url << "'," << "\n";
  str << _space << "enabled = true" << "\n";
  str << "}" << _end;

  return str.str();
}

bool github_url_exists(const std::string &url) {
  CURL *curl = curl_easy_init();
  if (!curl)
    return false;

  std::string full_url = "https://github.com/" + url;
  if (url.find("https://") != std::string::npos)
    full_url = url;
  else
    full_url = "https://github.com/" + url;
  curl_easy_setopt(curl, CURLOPT_URL, full_url.c_str());
  curl_easy_setopt(curl, CURLOPT_NOBODY, 1L);
  curl_easy_setopt(curl, CURLOPT_FOLLOWLOCATION, 1L);

  CURLcode res = curl_easy_perform(curl);

  long http_code = 0;
  curl_easy_getinfo(curl, CURLINFO_RESPONSE_CODE, &http_code);
  curl_easy_cleanup(curl);

  return res == CURLE_OK && http_code == 200;
}
std::string install_recommended_plugin_config(const std::string &plugin_name) {
  std::string raw_url =
      "https://raw.githubusercontent.com/KiamMota/lpm/main/plugins_config/" +
      plugin_name + ".lua";

  CURL *curl = curl_easy_init();
  if (!curl)
    throw std::runtime_error("failed to init curl");

  std::string response;

  auto write_cb = [](char *ptr, size_t size, size_t nmemb,
                     void *userdata) -> size_t {
    std::string *out = static_cast<std::string *>(userdata);
    out->append(ptr, size * nmemb);
    return size * nmemb;
  };

  curl_easy_setopt(curl, CURLOPT_URL, raw_url.c_str());
  curl_easy_setopt(curl, CURLOPT_WRITEFUNCTION, +write_cb);
  curl_easy_setopt(curl, CURLOPT_WRITEDATA, &response);
  curl_easy_setopt(curl, CURLOPT_FOLLOWLOCATION, 1L);
  curl_easy_setopt(curl, CURLOPT_USERAGENT, "lpm/1.0");

  CURLcode res = curl_easy_perform(curl);

  long http_code = 0;
  curl_easy_getinfo(curl, CURLINFO_RESPONSE_CODE, &http_code);
  curl_easy_cleanup(curl);

  if (res != CURLE_OK)
    throw std::runtime_error("curl error: " +
                             std::string(curl_easy_strerror(res)));

  if (http_code == 404)
    return ""; // não encontrou config no repo

  if (http_code != 200)
    throw std::runtime_error("unexpected HTTP " + std::to_string(http_code) +
                             " from repo");

  return response;
}
static std::string resolve_plugin_name(const std::string &name) {
  std::string result = name;

  size_t slash_pos = result.rfind('/');
  if (slash_pos != std::string::npos)
    result = result.substr(slash_pos + 1);

  if (result.size() > 4 && result.substr(result.size() - 4) == ".git")
    result = result.substr(0, result.size() - 4);

  for (const std::string suffix : {".nvim", "-nvim", ".neovim", "-neovim",
                                   ".vim", "-vim", ".lua", "-lua"}) {
    if (result.size() > suffix.size() &&
        result.substr(result.size() - suffix.size()) == suffix) {
      result = result.substr(0, result.size() - suffix.size());
      break;
    }
  }

  for (const std::string prefix : {"nvim-", "neovim-", "vim-"}) {
    if (result.size() > prefix.size() &&
        result.substr(0, prefix.size()) == prefix) {
      result = result.substr(prefix.size());
      break;
    }
  }

  std::transform(result.begin(), result.end(), result.begin(), ::tolower);
  std::replace(result.begin(), result.end(), '.', '-');
  return result;
}

namespace commands {
void install(std::vector<std::string> &commands) {
  if (commands.empty()) {
    cli::require_arg("install", "<github url>");
    return;
  }
  std::string plugin_github_url = commands.at(0);
  size_t slash_pos = plugin_github_url.rfind('/');
  if (slash_pos == std::string::npos) {
    std::cout << "Error: invalid GitHub URL: " << plugin_github_url
              << std::endl;
    return;
  }
  std::string plugin_name = resolve_plugin_name(plugin_github_url);
  std::cout << "resolved plugin name. (" << plugin_name << ")" << std::endl;
  std::string filepath = base::nvPath.plugins_path + "/" + plugin_name + ".lua";
  std::cout << "resolved plugin filepath. (" << filepath << ")" << std::endl;

  std::cout << "installing..." << std::endl;
  if (std::filesystem::exists(filepath)) {
    std::cout << "plugin already installed!" << std::endl;
    return;
  }
  if (!github_url_exists(plugin_github_url)) {
    std::cout
        << "Error: Could not connect to the provided URL (Status Code: 404)."
        << std::endl;
    return;
  }

  std::string file_content;
  try {
    std::string repo_config = install_recommended_plugin_config(plugin_name);
    if (!repo_config.empty()) {
      std::cout << "found config in lpm repo!" << std::endl;
      file_content = repo_config;
    }
  } catch (const std::exception &ex) {
    std::cout << "warning: could not fetch from lpm repo: " << ex.what()
              << std::endl;
  }

  if (file_content.empty()) {
    file_content = build_file_string(plugin_github_url.c_str());
  }
  try {
    fsio::write_file(filepath, file_content);
  } catch (const std::runtime_error &e) {
    std::cout << e.what() << std::endl;
  }

  std::cout << "installed!" << std::endl;
  sync();
  std::cout << "created in: " << filepath << std::endl;
}
} // namespace commands
