#include "base.hpp"
#include "cli_base.hpp"
#include "commands.hpp"
#include "curl/curl.h"
#include <cstddef>
#include <filesystem>
#include <fstream>
#include <iostream>
#include <sstream>
#include <string>
#include <vector>
static const std::string build_non_nested_table(const char *table_name,
                                                std::vector<std::string> vec,
                                                bool comma = true) {
  std::stringstream str;
  std::string _spc = "  ";
  str << _spc << table_name << " = ";

  str << "{";
  if (vec.empty())
    goto close_brackets;

  for (size_t i = 0; i < vec.size(); i++) {
    str << "'" << vec[i] << "'";
    if (i < vec.size() - 1)
      str << ", ";
  }
close_brackets:
  str << "}" << (comma ? "," : "\n");
  return str.str();
}

static const std::string build_file_string(
    const char *github_url, std::vector<std::string> dependencies = {},
    std::vector<std::string> opts = {}, std::vector<std::string> cmd = {},
    std::vector<std::string> keys = {}) {
  std::string _space = "  ";
  std::stringstream str;
  std::string _end = "\n";
  str << "-- file automatically generated by lazy.nvim cli.\n";
  str << "return {" << _end;
  // add github url
  str << _space << "'" << github_url << "'," << "\n";

  str << build_non_nested_table("dependencies", dependencies) << _end;
  str << build_non_nested_table("opts", opts) << _end;
  str << build_non_nested_table("cmd", cmd) << _end;
  str << build_non_nested_table("keys", keys) << _end;
  str << "}" << _end;

  return str.str();
}

bool github_url_exists(const std::string &url) {
  CURL *curl = curl_easy_init();
  if (!curl)
    return false;

  std::string full_url = "https://github.com/" + url;
  if (url.find("https://") != std::string::npos)
    full_url = url;
  else
    full_url = "https://github.com/" + url;
  curl_easy_setopt(curl, CURLOPT_URL, full_url.c_str());
  curl_easy_setopt(curl, CURLOPT_NOBODY, 1L); // só HEAD, sem baixar o body
  curl_easy_setopt(curl, CURLOPT_FOLLOWLOCATION, 1L);

  CURLcode res = curl_easy_perform(curl);

  long http_code = 0;
  curl_easy_getinfo(curl, CURLINFO_RESPONSE_CODE, &http_code);
  curl_easy_cleanup(curl);

  return res == CURLE_OK && http_code == 200;
}
static const std::string build_require(const char *plugin_name) {
  return "require(plugins." + std::string(plugin_name) + ")";
}
void prepend_to_file(const std::string &filepath, const std::string &content) {
  std::ifstream file_in(filepath);
  if (!file_in.is_open())
    throw std::runtime_error("failed to open file: " + filepath);

  std::stringstream buffer;
  buffer << file_in.rdbuf();
  file_in.close();

  std::ofstream file_out(filepath);
  if (!file_out.is_open())
    throw std::runtime_error("failed to write file: " + filepath);

  file_out << content << buffer.str(); // novo + original
  file_out.close();
}
namespace commands {

void install(std::vector<std::string> &commands) {
  if (commands.empty()) {
    cli::require_arg("install", "<github url>");
    return;
  }

  if (!base::is_lazy_installed()) {
    std::cout << "woops! you dont have lazy!" << std::endl;
    install_lazy();
  }

  std::string plugin_github_url = commands.at(0);
  std::string plugin_name =
      plugin_github_url.substr(plugin_github_url.rfind('/') + 1);
  std::string filepath = base::nvPath.plugins_path + "/" + plugin_name + ".lua";
  if (std::filesystem::exists(filepath)) {
    std::cout << "plugin already installed!" << std::endl;
    return;
  }

  std::cout << "installing '" << plugin_github_url << "' in '" << filepath
            << "'..." << std::endl;

  if (!github_url_exists(plugin_github_url)) {
    std::cout
        << "Error: Could not connect to the provided URL (Status Code: 404)."
        << std::endl;
    return;
  }

  std::string file_content = build_file_string(plugin_github_url.c_str());
  std::ofstream file(filepath);
  if (!file.is_open())
    std::cout << "fail to open file: " + filepath << std::endl;
  file << file_content;

  if (file.fail())
    std::cout << "fail to write file: " + filepath << std::endl;
  file.close();
  std::cout << "installed!" << std::endl;
  std::cout << file_content << std::endl;
  std::cout << "created in: " << filepath << std::endl;
  if (cli::msg_question("Do you want to insert it into init.lua ?")) {
    std::ofstream init_lua(base::nvPath.init_path);
    if (!init_lua.is_open()) {
      std::cout << "init.lua cannot be open." << std::endl;
      return;
    }
    prepend_to_file(base::nvPath.init_path, build_require(plugin_name.c_str()));
    std::cout << "done." << std::endl;
  }
}
} // namespace commands
