package commands

import (
	"io"
	"lpm/base"
	"lpm/cli"
	"net/http"
	"os"
	"strings"
)

func fallbackConfig(github_url string) string {
	var fallbackStr string = "-- autogenerated by lpm.\n"
	fallbackStr += "return " + "\n"
	fallbackStr += "{" + "\n"
	fallbackStr += "'" + github_url + ",'\n"
	fallbackStr += "opts = {},\n"
	fallbackStr += "dependencies = {},\n"
	fallbackStr += "enabled = true\n"
	fallbackStr += "}"

	return fallbackStr
}

func resolvePluginName(name string) string {
	result := name

	if i := strings.LastIndex(result, "/"); i != -1 {
		result = result[i+1:]
	}

	if strings.HasSuffix(result, ".git") {
		result = result[:len(result)-4]
	}

	suffixes := []string{
		".nvim", "-nvim",
		".neovim", "-neovim",
		".vim", "-vim",
		".lua", "-lua",
	}

	for _, s := range suffixes {
		if strings.HasSuffix(result, s) {
			result = result[:len(result)-len(s)]
			break
		}
	}

	result = strings.ToLower(result)
	result = strings.ReplaceAll(result, ".", "-")

	return result

}

func installRecommendedPluginConfig(pluginName string) (string, error) {
	var url string = "https://raw.githubusercontent.com/KiamMota/lpm/main/plugins_config/" + pluginName + ".lua"
	req, err := http.NewRequest("GET", url, nil)
	if err != nil {
		return "", err
	}

	req.Header.Set("User-Agent", "lpm-go/1.0")
	client := &http.Client{}

	resp, err := client.Do(req)
	if err != nil {
		return "", err
	}

	defer resp.Body.Close()

	if resp.StatusCode == 404 {
		return "", nil
	}
	if resp.StatusCode != 200 {
		return "net err", nil
	}

	body, err := io.ReadAll(resp.Body)
	if err != nil {
		return "", err
	}

	return string(body), nil

}

func Install(commands []string) {
	if len(commands) == 0 {
		cli.Required("install", "<github url>/<plugin name>")
	}

	var plugin_github_name string = commands[0]
	var plugin_name string = resolvePluginName(plugin_github_name)
	var plugin_path string = base.NvPath.PluginsPath + "/" + plugin_name

	if base.FileExists(plugin_path) {
		base.LpmLog("plugin already installed!", base.Ok)
		return
	}

	base.LpmLog("resolved plugin name ("+plugin_name+")", base.Ok)
	base.LpmLog("resolved plugin filepath ("+plugin_path+")", base.Ok)
	base.LpmLog("searching recommended plugin config...", base.Ok)

	var fileContent string
	var pluginConfigErr error
	fileContent, pluginConfigErr = installRecommendedPluginConfig(plugin_name)

	var baseConfig string = fallbackConfig(plugin_name)

	if pluginConfigErr != nil {
		base.LpmLog("config not find! inserting fallback config...", base.Ok)
		base.LpmLog(baseConfig, base.Ok)
	}

	base.LpmLog("find config!", base.Ok)

	base.LpmLog("installing plugin...", base.Ok)
	file, fileErr := os.Create(plugin_path)

	if fileErr != nil {
		base.LpmLog(fileErr.Error(), base.Err)
		base.LpmLog("removing file...", base.Ok)
		os.Remove(plugin_path)
	}

	file.WriteString(fileContent)
	base.LpmLog("installed!", base.Ok)
	base.LazySync()
	base.LpmLog("installed. enjoy!", base.Ok)

}
